MODULE mod_interfaces
  USE mod_procedures
  implicit none

  INTERFACE READVEC
    MODULE PROCEDURE READVEC_C,READVEC_R,READVEC_I
  END INTERFACE READVEC

  INTERFACE PRINTVEC
    MODULE PROCEDURE PRINTVEC_C,PRINTVEC_R,PRINTVEC_I
  END INTERFACE PRINTVEC

  INTERFACE PRINTMAT
    MODULE PROCEDURE PRINTMAT_C,PRINTMAT_R,PRINTMAT_I
  END INTERFACE PRINTMAT


END MODULE mod_interfaces